# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'root.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(711, 469)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.paginas = QtGui.QStackedWidget(self.centralwidget)
        self.paginas.setGeometry(QtCore.QRect(0, 0, 711, 391))
        self.paginas.setObjectName(_fromUtf8("paginas"))
        self.pagina_ventas = QtGui.QWidget()
        self.pagina_ventas.setObjectName(_fromUtf8("pagina_ventas"))
        self.ventas_existencia = QtGui.QTableWidget(self.pagina_ventas)
        self.ventas_existencia.setGeometry(QtCore.QRect(0, 80, 401, 301))
        self.ventas_existencia.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ventas_existencia.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ventas_existencia.setTextElideMode(QtCore.Qt.ElideRight)
        self.ventas_existencia.setObjectName(_fromUtf8("ventas_existencia"))
        self.ventas_existencia.setColumnCount(4)
        self.ventas_existencia.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ventas_existencia.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ventas_existencia.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ventas_existencia.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.ventas_existencia.setHorizontalHeaderItem(3, item)
        self.gridLayoutWidget = QtGui.QWidget(self.pagina_ventas)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 251, 72))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 2)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.venta_buscar_nombre = QtGui.QLineEdit(self.gridLayoutWidget)
        self.venta_buscar_nombre.setObjectName(_fromUtf8("venta_buscar_nombre"))
        self.gridLayout.addWidget(self.venta_buscar_nombre, 1, 1, 1, 1)
        self.venta_buscar = QtGui.QPushButton(self.gridLayoutWidget)
        self.venta_buscar.setObjectName(_fromUtf8("venta_buscar"))
        self.gridLayout.addWidget(self.venta_buscar, 2, 0, 1, 2)
        self.ventas_final = QtGui.QTableWidget(self.pagina_ventas)
        self.ventas_final.setGeometry(QtCore.QRect(410, 80, 301, 301))
        self.ventas_final.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ventas_final.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ventas_final.setObjectName(_fromUtf8("ventas_final"))
        self.ventas_final.setColumnCount(3)
        self.ventas_final.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ventas_final.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ventas_final.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ventas_final.setHorizontalHeaderItem(2, item)
        self.ventas_vender = QtGui.QPushButton(self.pagina_ventas)
        self.ventas_vender.setEnabled(False)
        self.ventas_vender.setGeometry(QtCore.QRect(410, 30, 83, 24))
        self.ventas_vender.setAutoDefault(True)
        self.ventas_vender.setObjectName(_fromUtf8("ventas_vender"))
        self.ventas_cancelar = QtGui.QPushButton(self.pagina_ventas)
        self.ventas_cancelar.setEnabled(False)
        self.ventas_cancelar.setGeometry(QtCore.QRect(540, 30, 83, 24))
        self.ventas_cancelar.setAutoDefault(True)
        self.ventas_cancelar.setObjectName(_fromUtf8("ventas_cancelar"))
        self.paginas.addWidget(self.pagina_ventas)
        self.pagina_inventario = QtGui.QWidget()
        self.pagina_inventario.setObjectName(_fromUtf8("pagina_inventario"))
        self.toolBox = QtGui.QToolBox(self.pagina_inventario)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 711, 391))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.ingresar_productos = QtGui.QWidget()
        self.ingresar_productos.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.ingresar_productos.setObjectName(_fromUtf8("ingresar_productos"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.ingresar_productos)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 271, 251))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.producto_nombre = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.producto_nombre.setText(_fromUtf8(""))
        self.producto_nombre.setObjectName(_fromUtf8("producto_nombre"))
        self.gridLayout_7.addWidget(self.producto_nombre, 0, 2, 1, 1)
        self.producto_precio = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.producto_precio.setObjectName(_fromUtf8("producto_precio"))
        self.gridLayout_7.addWidget(self.producto_precio, 1, 2, 1, 1)
        self.producto_cantidad = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.producto_cantidad.setObjectName(_fromUtf8("producto_cantidad"))
        self.gridLayout_7.addWidget(self.producto_cantidad, 2, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 3, 0, 1, 1)
        self.producto_ingresar = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.producto_ingresar.setAutoDefault(True)
        self.producto_ingresar.setObjectName(_fromUtf8("producto_ingresar"))
        self.gridLayout_7.addWidget(self.producto_ingresar, 4, 2, 1, 1)
        self.producto_marca = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.producto_marca.setObjectName(_fromUtf8("producto_marca"))
        self.gridLayout_7.addWidget(self.producto_marca, 3, 2, 1, 1)
        self.toolBox.addItem(self.ingresar_productos, _fromUtf8(""))
        self.actualizar_productos = QtGui.QWidget()
        self.actualizar_productos.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.actualizar_productos.setObjectName(_fromUtf8("actualizar_productos"))
        self.gridLayoutWidget_8 = QtGui.QWidget(self.actualizar_productos)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 561, 291))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 6, 5, 1, 1)
        self.actualizar_producto = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.actualizar_producto.setObjectName(_fromUtf8("actualizar_producto"))
        self.gridLayout_8.addWidget(self.actualizar_producto, 6, 2, 1, 1)
        self.actualizar_buscar = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.actualizar_buscar.setAutoDefault(True)
        self.actualizar_buscar.setObjectName(_fromUtf8("actualizar_buscar"))
        self.gridLayout_8.addWidget(self.actualizar_buscar, 6, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 6, 3, 1, 1)
        self.actualizar_lista = QtGui.QTableWidget(self.gridLayoutWidget_8)
        self.actualizar_lista.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.actualizar_lista.setObjectName(_fromUtf8("actualizar_lista"))
        self.actualizar_lista.setColumnCount(5)
        self.actualizar_lista.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.actualizar_lista.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.actualizar_lista.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.actualizar_lista.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.actualizar_lista.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.actualizar_lista.setHorizontalHeaderItem(4, item)
        self.gridLayout_8.addWidget(self.actualizar_lista, 7, 1, 1, 5)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 6, 0, 1, 1)
        self.actualizar_actualizar = QtGui.QPushButton(self.actualizar_productos)
        self.actualizar_actualizar.setEnabled(False)
        self.actualizar_actualizar.setGeometry(QtCore.QRect(590, 10, 83, 24))
        self.actualizar_actualizar.setAutoDefault(True)
        self.actualizar_actualizar.setObjectName(_fromUtf8("actualizar_actualizar"))
        self.toolBox.addItem(self.actualizar_productos, _fromUtf8(""))
        self.eliminar_productos = QtGui.QWidget()
        self.eliminar_productos.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.eliminar_productos.setObjectName(_fromUtf8("eliminar_productos"))
        self.gridLayoutWidget_9 = QtGui.QWidget(self.eliminar_productos)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 461, 301))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_9)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_9.addWidget(self.label_14, 1, 0, 1, 1)
        self.eliminar_buscar_2 = QtGui.QPushButton(self.gridLayoutWidget_9)
        self.eliminar_buscar_2.setAutoDefault(True)
        self.eliminar_buscar_2.setObjectName(_fromUtf8("eliminar_buscar_2"))
        self.gridLayout_9.addWidget(self.eliminar_buscar_2, 1, 4, 1, 1)
        self.eliminar_producto = QtGui.QLineEdit(self.gridLayoutWidget_9)
        self.eliminar_producto.setObjectName(_fromUtf8("eliminar_producto"))
        self.gridLayout_9.addWidget(self.eliminar_producto, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 1, 3, 1, 1)
        self.eliminar_lista_2 = QtGui.QTableWidget(self.gridLayoutWidget_9)
        self.eliminar_lista_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.eliminar_lista_2.setObjectName(_fromUtf8("eliminar_lista_2"))
        self.eliminar_lista_2.setColumnCount(4)
        self.eliminar_lista_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_9.addWidget(self.eliminar_lista_2, 3, 1, 1, 5)
        self.gridLayoutWidget_10 = QtGui.QWidget(self.eliminar_productos)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(500, 0, 201, 80))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.eliminar_id_2 = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.eliminar_id_2.setObjectName(_fromUtf8("eliminar_id_2"))
        self.gridLayout_10.addWidget(self.eliminar_id_2, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.eliminar_eliminar_2 = QtGui.QPushButton(self.gridLayoutWidget_10)
        self.eliminar_eliminar_2.setEnabled(False)
        self.eliminar_eliminar_2.setAutoDefault(True)
        self.eliminar_eliminar_2.setObjectName(_fromUtf8("eliminar_eliminar_2"))
        self.gridLayout_10.addWidget(self.eliminar_eliminar_2, 1, 0, 1, 2)
        self.toolBox.addItem(self.eliminar_productos, _fromUtf8(""))
        self.paginas.addWidget(self.pagina_inventario)
        self.pagina_usuarios = QtGui.QWidget()
        self.pagina_usuarios.setObjectName(_fromUtf8("pagina_usuarios"))
        self.toolBox_2 = QtGui.QToolBox(self.pagina_usuarios)
        self.toolBox_2.setGeometry(QtCore.QRect(0, 0, 711, 391))
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.ingresar_usuario = QtGui.QWidget()
        self.ingresar_usuario.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.ingresar_usuario.setObjectName(_fromUtf8("ingresar_usuario"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.ingresar_usuario)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 271, 201))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ingresar_password = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.ingresar_password.setObjectName(_fromUtf8("ingresar_password"))
        self.gridLayout_2.addWidget(self.ingresar_password, 1, 2, 1, 1)
        self.ingresar_ingresar = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.ingresar_ingresar.setAutoDefault(True)
        self.ingresar_ingresar.setObjectName(_fromUtf8("ingresar_ingresar"))
        self.gridLayout_2.addWidget(self.ingresar_ingresar, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.ingresar_nombre = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.ingresar_nombre.setText(_fromUtf8(""))
        self.ingresar_nombre.setObjectName(_fromUtf8("ingresar_nombre"))
        self.gridLayout_2.addWidget(self.ingresar_nombre, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.permiso_usuario = QtGui.QRadioButton(self.groupBox_3)
        self.permiso_usuario.setGeometry(QtCore.QRect(20, 30, 100, 19))
        self.permiso_usuario.setObjectName(_fromUtf8("permiso_usuario"))
        self.permiso_administrador = QtGui.QRadioButton(self.groupBox_3)
        self.permiso_administrador.setGeometry(QtCore.QRect(20, 70, 100, 19))
        self.permiso_administrador.setChecked(False)
        self.permiso_administrador.setObjectName(_fromUtf8("permiso_administrador"))
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.toolBox_2.addItem(self.ingresar_usuario, _fromUtf8(""))
        self.modificar_usuario = QtGui.QWidget()
        self.modificar_usuario.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.modificar_usuario.setObjectName(_fromUtf8("modificar_usuario"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.modificar_usuario)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 471, 301))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.modificar_buscar = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.modificar_buscar.setAutoDefault(True)
        self.modificar_buscar.setObjectName(_fromUtf8("modificar_buscar"))
        self.gridLayout_3.addWidget(self.modificar_buscar, 2, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 2, 3, 1, 1)
        self.modificar_lista = QtGui.QTableWidget(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modificar_lista.sizePolicy().hasHeightForWidth())
        self.modificar_lista.setSizePolicy(sizePolicy)
        self.modificar_lista.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.modificar_lista.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.modificar_lista.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.modificar_lista.setObjectName(_fromUtf8("modificar_lista"))
        self.modificar_lista.setColumnCount(4)
        self.modificar_lista.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.modificar_lista.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.modificar_lista.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.modificar_lista.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.modificar_lista.setHorizontalHeaderItem(3, item)
        self.modificar_lista.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout_3.addWidget(self.modificar_lista, 4, 1, 1, 3)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.modificar_usuario)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(470, 0, 241, 301))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.modificar_modificar = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.modificar_modificar.setEnabled(False)
        self.modificar_modificar.setAutoDefault(True)
        self.modificar_modificar.setObjectName(_fromUtf8("modificar_modificar"))
        self.gridLayout_4.addWidget(self.modificar_modificar, 7, 1, 1, 1)
        self.modificar_usuario_2 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.modificar_usuario_2.setObjectName(_fromUtf8("modificar_usuario_2"))
        self.gridLayout_4.addWidget(self.modificar_usuario_2, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.modificar_password = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.modificar_password.setObjectName(_fromUtf8("modificar_password"))
        self.gridLayout_4.addWidget(self.modificar_password, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.modificar_nuevo_nombre = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.modificar_nuevo_nombre.setObjectName(_fromUtf8("modificar_nuevo_nombre"))
        self.gridLayout_4.addWidget(self.modificar_nuevo_nombre, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.gridLayoutWidget_4)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.modificar_administrador = QtGui.QRadioButton(self.groupBox_2)
        self.modificar_administrador.setGeometry(QtCore.QRect(20, 20, 100, 19))
        self.modificar_administrador.setObjectName(_fromUtf8("modificar_administrador"))
        self.modificar_usuario_3 = QtGui.QRadioButton(self.groupBox_2)
        self.modificar_usuario_3.setGeometry(QtCore.QRect(20, 50, 100, 19))
        self.modificar_usuario_3.setObjectName(_fromUtf8("modificar_usuario_3"))
        self.gridLayout_4.addWidget(self.groupBox_2, 5, 1, 1, 1)
        self.toolBox_2.addItem(self.modificar_usuario, _fromUtf8(""))
        self.eliminarusuario = QtGui.QWidget()
        self.eliminarusuario.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.eliminarusuario.setObjectName(_fromUtf8("eliminarusuario"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.eliminarusuario)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 371, 291))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.eliminar_buscar = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.eliminar_buscar.setAutoDefault(True)
        self.eliminar_buscar.setObjectName(_fromUtf8("eliminar_buscar"))
        self.gridLayout_5.addWidget(self.eliminar_buscar, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 0, 3, 1, 1)
        self.eliminar_lista = QtGui.QTableWidget(self.gridLayoutWidget_5)
        self.eliminar_lista.setObjectName(_fromUtf8("eliminar_lista"))
        self.eliminar_lista.setColumnCount(2)
        self.eliminar_lista.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.eliminar_lista.setHorizontalHeaderItem(1, item)
        self.gridLayout_5.addWidget(self.eliminar_lista, 1, 1, 1, 3)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.eliminarusuario)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(420, 20, 231, 74))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.eliminar_id = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.eliminar_id.setObjectName(_fromUtf8("eliminar_id"))
        self.gridLayout_6.addWidget(self.eliminar_id, 0, 1, 1, 1)
        self.eliminar_eliminar = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.eliminar_eliminar.setEnabled(False)
        self.eliminar_eliminar.setAutoDefault(True)
        self.eliminar_eliminar.setObjectName(_fromUtf8("eliminar_eliminar"))
        self.gridLayout_6.addWidget(self.eliminar_eliminar, 1, 0, 1, 2)
        self.toolBox_2.addItem(self.eliminarusuario, _fromUtf8(""))
        self.paginas.addWidget(self.pagina_usuarios)
        self.pagina_corte = QtGui.QWidget()
        self.pagina_corte.setObjectName(_fromUtf8("pagina_corte"))
        self.gridLayoutWidget_11 = QtGui.QWidget(self.pagina_corte)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(470, 10, 91, 101))
        self.gridLayoutWidget_11.setObjectName(_fromUtf8("gridLayoutWidget_11"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.corte_total = QtGui.QLineEdit(self.gridLayoutWidget_11)
        self.corte_total.setObjectName(_fromUtf8("corte_total"))
        self.gridLayout_11.addWidget(self.corte_total, 3, 0, 1, 1)
        self.corte_generar = QtGui.QPushButton(self.gridLayoutWidget_11)
        self.corte_generar.setObjectName(_fromUtf8("corte_generar"))
        self.gridLayout_11.addWidget(self.corte_generar, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_11)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_11)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 2, 0, 1, 1)
        self.corte_mostrar = QtGui.QTableWidget(self.pagina_corte)
        self.corte_mostrar.setGeometry(QtCore.QRect(0, 0, 221, 389))
        self.corte_mostrar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.corte_mostrar.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.corte_mostrar.setObjectName(_fromUtf8("corte_mostrar"))
        self.corte_mostrar.setColumnCount(2)
        self.corte_mostrar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.corte_mostrar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.corte_mostrar.setHorizontalHeaderItem(1, item)
        self.paginas.addWidget(self.pagina_corte)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.barra_salir = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/1211729599.2.2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barra_salir.setIcon(icon)
        self.barra_salir.setPriority(QtGui.QAction.LowPriority)
        self.barra_salir.setObjectName(_fromUtf8("barra_salir"))
        self.barra_venta = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/bag.2.2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barra_venta.setIcon(icon1)
        self.barra_venta.setObjectName(_fromUtf8("barra_venta"))
        self.barra_usuarios = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/nuevo-icono-de-grupo-de-usuario-14853.2.2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barra_usuarios.setIcon(icon2)
        self.barra_usuarios.setObjectName(_fromUtf8("barra_usuarios"))
        self.barra_corte = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Billing-icon.2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barra_corte.setIcon(icon3)
        self.barra_corte.setObjectName(_fromUtf8("barra_corte"))
        self.barra_inventario = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/inventory_icon.2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barra_inventario.setIcon(icon4)
        self.barra_inventario.setObjectName(_fromUtf8("barra_inventario"))
        self.menu_salir = QtGui.QAction(MainWindow)
        self.menu_salir.setObjectName(_fromUtf8("menu_salir"))
        self.menu_info = QtGui.QAction(MainWindow)
        self.menu_info.setObjectName(_fromUtf8("menu_info"))
        self.menuArchivo.addAction(self.menu_salir)
        self.menuAbout.addAction(self.menu_info)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.barra_venta)
        self.toolBar.addAction(self.barra_inventario)
        self.toolBar.addAction(self.barra_usuarios)
        self.toolBar.addAction(self.barra_corte)
        self.toolBar.addAction(self.barra_salir)

        self.retranslateUi(MainWindow)
        self.paginas.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.venta_buscar_nombre, self.ventas_vender)
        MainWindow.setTabOrder(self.ventas_vender, self.ventas_existencia)
        MainWindow.setTabOrder(self.ventas_existencia, self.ventas_final)
        MainWindow.setTabOrder(self.ventas_final, self.ingresar_nombre)
        MainWindow.setTabOrder(self.ingresar_nombre, self.ingresar_password)
        MainWindow.setTabOrder(self.ingresar_password, self.permiso_usuario)
        MainWindow.setTabOrder(self.permiso_usuario, self.permiso_administrador)
        MainWindow.setTabOrder(self.permiso_administrador, self.ingresar_ingresar)
        MainWindow.setTabOrder(self.ingresar_ingresar, self.modificar_buscar)
        MainWindow.setTabOrder(self.modificar_buscar, self.modificar_nuevo_nombre)
        MainWindow.setTabOrder(self.modificar_nuevo_nombre, self.modificar_password)
        MainWindow.setTabOrder(self.modificar_password, self.modificar_administrador)
        MainWindow.setTabOrder(self.modificar_administrador, self.modificar_usuario_3)
        MainWindow.setTabOrder(self.modificar_usuario_3, self.modificar_modificar)
        MainWindow.setTabOrder(self.modificar_modificar, self.modificar_lista)
        MainWindow.setTabOrder(self.modificar_lista, self.eliminar_buscar)
        MainWindow.setTabOrder(self.eliminar_buscar, self.eliminar_id)
        MainWindow.setTabOrder(self.eliminar_id, self.eliminar_eliminar)
        MainWindow.setTabOrder(self.eliminar_eliminar, self.eliminar_lista)
        MainWindow.setTabOrder(self.eliminar_lista, self.producto_nombre)
        MainWindow.setTabOrder(self.producto_nombre, self.producto_precio)
        MainWindow.setTabOrder(self.producto_precio, self.producto_cantidad)
        MainWindow.setTabOrder(self.producto_cantidad, self.actualizar_producto)
        MainWindow.setTabOrder(self.actualizar_producto, self.actualizar_buscar)
        MainWindow.setTabOrder(self.actualizar_buscar, self.actualizar_lista)
        MainWindow.setTabOrder(self.actualizar_lista, self.actualizar_actualizar)
        MainWindow.setTabOrder(self.actualizar_actualizar, self.eliminar_buscar_2)
        MainWindow.setTabOrder(self.eliminar_buscar_2, self.eliminar_producto)
        MainWindow.setTabOrder(self.eliminar_producto, self.eliminar_lista_2)
        MainWindow.setTabOrder(self.eliminar_lista_2, self.eliminar_id_2)
        MainWindow.setTabOrder(self.eliminar_id_2, self.eliminar_eliminar_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Punto de venta", None))
        item = self.ventas_existencia.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.ventas_existencia.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto", None))
        item = self.ventas_existencia.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio", None))
        item = self.ventas_existencia.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Existencia", None))
        self.label_18.setText(_translate("MainWindow", "Buscar producto", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Nombre producto</p></body></html>", None))
        self.venta_buscar.setText(_translate("MainWindow", "Buscar", None))
        item = self.ventas_final.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.ventas_final.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto", None))
        item = self.ventas_final.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio", None))
        self.ventas_vender.setText(_translate("MainWindow", "Vender", None))
        self.ventas_cancelar.setText(_translate("MainWindow", "Cancelar", None))
        self.toolBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "Producto", None))
        self.label_5.setText(_translate("MainWindow", "Precio", None))
        self.label_13.setText(_translate("MainWindow", "Cantidad", None))
        self.label_20.setText(_translate("MainWindow", "Marca", None))
        self.producto_ingresar.setText(_translate("MainWindow", "Ingresar", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ingresar_productos), _translate("MainWindow", "Ingresar productos", None))
        self.actualizar_buscar.setText(_translate("MainWindow", "Buscar", None))
        item = self.actualizar_lista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.actualizar_lista.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto", None))
        item = self.actualizar_lista.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio", None))
        item = self.actualizar_lista.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cantidad", None))
        item = self.actualizar_lista.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Marca", None))
        self.label_16.setText(_translate("MainWindow", "Producto", None))
        self.actualizar_actualizar.setText(_translate("MainWindow", "Actualizar", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.actualizar_productos), _translate("MainWindow", "Actualizar productos", None))
        self.label_14.setText(_translate("MainWindow", "Producto", None))
        self.eliminar_buscar_2.setText(_translate("MainWindow", "Buscar", None))
        item = self.eliminar_lista_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.eliminar_lista_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto", None))
        item = self.eliminar_lista_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio", None))
        item = self.eliminar_lista_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cantidad", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Id del producto</p><p>a eliminar</p></body></html>", None))
        self.eliminar_eliminar_2.setText(_translate("MainWindow", "Eliminar", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.eliminar_productos), _translate("MainWindow", "Eliminar productos", None))
        self.ingresar_ingresar.setText(_translate("MainWindow", "Ingresar", None))
        self.label_4.setText(_translate("MainWindow", "Contraseña", None))
        self.label_3.setText(_translate("MainWindow", "Usuario", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Permisos de usuario", None))
        self.permiso_usuario.setText(_translate("MainWindow", "Usuario", None))
        self.permiso_administrador.setText(_translate("MainWindow", "Administrador", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.ingresar_usuario), _translate("MainWindow", "Ingresar usuario", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Usuario </p><p>en la bd</p></body></html>", None))
        self.modificar_buscar.setText(_translate("MainWindow", "Buscar", None))
        item = self.modificar_lista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.modificar_lista.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.modificar_lista.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contraseña", None))
        item = self.modificar_lista.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Permisos", None))
        self.modificar_modificar.setText(_translate("MainWindow", "Modificar", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Nuevo</p><p>nombre</p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Nueva</p><p>Contraseña</p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Usuario a</p><p>modificar</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Aterar usuario", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Permisos", None))
        self.modificar_administrador.setText(_translate("MainWindow", "Administrador", None))
        self.modificar_usuario_3.setText(_translate("MainWindow", "Usuario", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.modificar_usuario), _translate("MainWindow", "Modificar usuario", None))
        self.eliminar_buscar.setText(_translate("MainWindow", "Buscar", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Usuarios</p><p>en la BD</p><p><br/></p></body></html>", None))
        item = self.eliminar_lista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.eliminar_lista.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Usuario", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Id de el usuario</p><p>a eliminar</p></body></html>", None))
        self.eliminar_eliminar.setText(_translate("MainWindow", "Eliminar", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.eliminarusuario), _translate("MainWindow", "Eliminar usuario", None))
        self.corte_generar.setText(_translate("MainWindow", "ok", None))
        self.label_2.setText(_translate("MainWindow", "Generar corte", None))
        self.label_19.setText(_translate("MainWindow", "Total", None))
        item = self.corte_mostrar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Producto", None))
        item = self.corte_mostrar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "precio", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.barra_salir.setText(_translate("MainWindow", "Salir", None))
        self.barra_salir.setToolTip(_translate("MainWindow", "salir del programa", None))
        self.barra_venta.setText(_translate("MainWindow", "Venta", None))
        self.barra_venta.setToolTip(_translate("MainWindow", "realizar venta", None))
        self.barra_usuarios.setText(_translate("MainWindow", "Usuario", None))
        self.barra_usuarios.setToolTip(_translate("MainWindow", "agregar usuario", None))
        self.barra_corte.setText(_translate("MainWindow", "Corte", None))
        self.barra_corte.setToolTip(_translate("MainWindow", "corte de caja", None))
        self.barra_inventario.setText(_translate("MainWindow", "Inventario", None))
        self.barra_inventario.setToolTip(_translate("MainWindow", "inventario", None))
        self.menu_salir.setText(_translate("MainWindow", "Salir", None))
        self.menu_info.setText(_translate("MainWindow", "Acerca de", None))

import iconos_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

